sudo: false
services:
- docker
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
language: java
jdk:
- oraclejdk8
env:
  matrix:
  - TERM=dumb WONKY_TENANTS_FILE=./orgs_ignored.yaml
  global:
  - secure: YynxQ8ZEPhnPo3bgAJqZ4l0gvUqHLV+D7eMS0/bmxR3PkCjVjZmW80UKJnj2a4fXOX6AI1snWp8WfbGjgV7gmoNYeFdk47Ym4UQR8yXPaAq1sf4IZXJmQ4j1cFLGDQgsdTsUbZwcIJYwPt7BN0ecOWtscr9P1ohxlGsVnKw0k51qqRi0YmpRf6SWEqwkAw/lz32ukHQH4phguUBtw9+YV2C5y+fqSMByidLFeengInwncCos5cFUPOSqDzjxbG1Q+fUN9UQrGbCs9DZV5cTQoDxo9NA6cNJo6cTmVKx1kh2vC8aQSw6TuYiZJIltH84LchL5qQ81A1/fVR/CXy+UWH2uxbWVwtQ8ttH+eu9aCCOnPjewRAu0blimgixTZHl2mfHGoN3vybFT8krwZEPeqgYile095BVai9P/0R0P2aAvsHz1tc5e3IC0axPjav8eETZv89ohELfLdbWO289FsVvTxTCkpagBHE35651RAXyP2dhctKLnqfhsfvaerwTChgf2q7Xddlp9pfmZwNeAQ/19xp+cEwdlZEq4H+LU3oecsWY5J2ie0qdpbXnoL9z2xaNP/ZScdSHadlauc1Qo8xZnPy/kFQ6vdrqW0DlxmK5SZoGpBJCuMdMUMog3VX6/W0tgNkypS+FhD8sp1MfUDnU3mInSbfp3x4rJA5ftq44=
  - secure: HRwJQXRVUkGz90S7TF7TUsk1vVDMpecgmnF8V/DlBRQIgxuMrFMXk5HvlfPhy9BrJb83oviIVXtttC/Kkf2FWxPOa8ifHQDiLZC1Le74Cfl4lGiWCSj2E0NVxh64UiZjWNFy8JI+ZVH1NO34UNc67xbbcryKdIKffLlFzJKdfAbFnfOowsykJoRMPXGccyO6NipFXDy+pOsjjq61XvrsiQqW1Kfv5WcCPwIIKP0A0R0eFb1/7T6K2Fe+eeBotq3nxTMtNqzUeQzxyeeCusiO0OTzy+sS2eimFRUOdFXc39PQjqETM0ly5kj9IMzJuNuKJZq6IDOcUCInBduQXQhmkBeiThED5OSzdvbtWnPKxfTZ7069oG8M8LOUmmIODRdQWl9rvtJrKP0JodiVNzrJXeb2SG3bP5kANy7s9nEqmK3IzZtHDisFUcIqkDzL1e9lDYAbEyE/sVczDidD+gajyGPDHMC/K7aXABA15l0iCYStE0J6rZA14ztM9dNKIHjAhcFrS/sr/j6ol/pRWZahlq4uYKElDu3LhFRVMby4jaPjide1JUzZWsC8JjS6r8bcSXdiEL9ykcTbPYCCzz0g580YjpDy7R9H6/OLRYbAFlbwwiQvalZQ/nD5LLx7FTkzeCC209VVA839vXYm/xVyK/3vpxGxwQ/fy75SlYUH1CU=
install: true
before_script:
- "./gradlew --version"
script:
- "./gradlew jacocoTestReport pushImage --warning-mode=all"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- openssl aes-256-cbc -K $encrypted_55795232bcfe_key -iv $encrypted_55795232bcfe_iv
  -in orgs_ignored.yaml.enc -out orgs_ignored.yaml -d
