sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
language: java
jdk:
- oraclejdk8
env:
- TERM=dumb WONKY_TENANTS_FILE=./orgs_ignored.yaml
install: true
before_script:
- "./gradlew --version"
script:
- "./gradlew jacocoTestReport"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- openssl aes-256-cbc -K $encrypted_55795232bcfe_key -iv $encrypted_55795232bcfe_iv
  -in orgs_ignored.yaml.enc -out orgs_ignored.yaml -d
