micronaut:
  application:
    name: wonky
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths:
          - classpath:html
      static:
        enabled: true
        mapping: /static/**
        paths:
          - classpath:html
  server:
    port: 8080
tracing:
  jaeger:
    enabled: true
